---
title: "Lab_2"
author: "Karla Palos "
output: github_document
---

### Lab 1

```{r}
library(readxl)
hospitals <- read_excel("../data/hospitals.xls")
cancer <- read_excel("../data/cancer.xls")
hospitalsM<- as.matrix(hospitals) # M = matrix
```


Problem  a. 
```{r}
library(dplyr)
library(ggplot2)
new_data<- data.frame(hospitalsM)



ggplot(data=hospitals, aes(new_data$X.discharges.)) + geom_histogram() +xlab("discharges")
ggplot(data=hospitals, aes(new_data$X.beds.)) + geom_histogram() +xlab("beds")

```


Problem b.
```{r}
colMeans(hospitalsM) #column means 

var(hospitalsM) # variance
sd(hospitalsM[,1]) #standard deviation
sd(hospitalsM[,2])

```


Problem c.
```{r}

pop <- hospitalsM[,1] #pop =population
num_samples <- 1000
sample_size <- 25
my_sample <- sample(pop,sample_size);

#we will run this function many times
find_mean <- function(){
  resample <- my_sample %>% sample(replace=TRUE)
  mean(resample)
}

#create a vector of means
means <-  replicate(num_samples, find_mean())

#find SE of the sample mean
sd(means)

# histogram

my_data <- data.frame(means)

#make simple histogram
my_data %>% ggplot(aes(x=means)) + geom_histogram(binwidth=10)

```


Problem d.
```{r}

# estimating mean from sample of size 25

my_sample <- sample(pop,sample_size);

mean(my_sample)

```


Problem e.
```{r}


# estimate of sigma^2

sigma_hat<- sqrt( var(my_sample)*(1-25/393)) 


```


Problem f.
```{r}
mean(hospitalsM[,1])

#u=up
#l=low

CI_l = mean(my_sample) - 1.96*(sigma_hat)*(1/5)
CI_u = mean(my_sample) + 1.96*(sigma_hat)*(1/5)

CI_l
CI_u

```


Problem g. 
```{r}
sample_size = 100
my_sample <- sample(pop,sample_size)

mean(my_sample)

sigma_hat<- sqrt(var(my_sample)*(1- 100/393) )


mean(hospitalsM[,1])

CI_l = mean(my_sample) - 1.96*(sigma_hat)*(1/10)
CI_u = mean(my_sample) + 1.96*(sigma_hat)*(1/10)

CI_l
CI_u


```









